services:
  controller:
    build: ./controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - worker_network

  worker:
    build: ./worker
    image: worker:latest
    networks:
      - worker_network

networks:
  worker_network:
    driver: bridge
    name: worker_network
