title: |md
  # System Architecture
| {near: top-center}

tasks: User Defined Tasks {
  shape: cylinder
  style.multiple: true
}

controller: Controller {
  shape: rectangle

  analyzer: Task Analyzer
  code_gen: Code Generator
  executor_mgr: Executor Manager
  server: Server
  state: State
}

workers: Workers {
  shape: circle
  style.multiple: true
}

user: User {
  shape: person
}

control_plane: Control Plane {
  web_ui: Web UI
}


controller.analyzer -> tasks: Analyze task metadata
controller.code_gen -> controller.analyzer: Get task metadata

controller.executor_mgr -> controller.code_gen: Get generated task code
controller.executor_mgr -> workers: Spawns and manages
workers -> controller.executor_mgr -> controller.state: Status updates

# Define connections
user -> control_plane.web_ui: Interacts

control_plane.web_ui <-> controller.server: Requests
controller.server -> controller.executor_mgr: Execution requests

controller.server -> controller.state: Status updates


style: {
  fill: "#f5f5f5"
  stroke: "#333"
  stroke-width: 2
  font-size: 14
}
